export default {
  ADD_TO_SHIP: 'ADD_TO_SHIP',
  CLEAR_LOADING: 'CLEAR_LOADING',
  LOAD_CHARACTER_BY_ID: 'LOAD_CHARACTER_BY_ID',
  LOAD_CHARACTERS: 'LOAD_CHARACTERS',
  LOAD_PLANET_BY_ID: 'LOAD_PLANET_BY_ID',
  LOAD_RANDOM_CHARACTER: 'LOAD_RANDOM_CHARACTER',
  LOAD_RANDOM_PLANET: 'LOAD_RANDOM_PLANET',
  LOAD_SHIP_CHARACTER_BY_ID: 'LOAD_SHIP_CHARACTER_BY_ID',
  LOADING: 'LOADING',
  REMOVE_CHARACTER: 'REMOVE_CHARACTER',
};
